name: Auto Deploy Portfolio
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Update Web Files and Restart
        run: |
          # --no-g and --no-p prevents permission/group sync errors
          # --exclude avoids uploading your hidden git config files
          rsync -avz --delete --no-g --no-p \
          --exclude '.git/' \
          --exclude '.github/' \
          ./ /home/cheesky/minecraft/html/

          # Move to the directory containing your docker-compose.yml
          cd /home/cheesky/minecraft/

          # Refresh only the nginx container
          docker compose up -d --build fluffy_main
